fixtures:
  repositories:
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo.git
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: git://github.com/puppetlabs/puppetlabs-concat.git
    firewall: git://github.com/puppetlabs/puppetlabs-firewall.git
    python: git@github.com:jmchilton/puppet-python.git
  symlinks:
    biocloudcentral: "#{source_dir}"
